// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZPqm5ZZE2saLTiobcI9ElhVIzCm3yPTk',
    appId: '1:143428416686:web:934e3148b677d6ee47a93f',
    messagingSenderId: '143428416686',
    projectId: 'expese-d584c',
    authDomain: 'expese-d584c.firebaseapp.com',
    storageBucket: 'expese-d584c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZCgu1hIT87MH5wAHjsPoL584M69YygZ8',
    appId: '1:143428416686:android:265aa1ec5f00e1a947a93f',
    messagingSenderId: '143428416686',
    projectId: 'expese-d584c',
    storageBucket: 'expese-d584c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrxIT0GznBsF94oAUuUSy3DwemXnSXnxE',
    appId: '1:143428416686:ios:383a6b4b3ebf1b5847a93f',
    messagingSenderId: '143428416686',
    projectId: 'expese-d584c',
    storageBucket: 'expese-d584c.firebasestorage.app',
    iosBundleId: 'com.example.expense',
  );
}
